language: rust
cache: cargo
rust:
  - 1.38.0
  - 1.39.0
  - 1.40.0
env:
  REDIS_URL=redis://127.0.0.1
before_script:
  - cargo build --verbose --all
  - sudo redis-server --loadmodule target/debug/libredis_shield.dylib
script:
  - cargo test --verbose --all
