dist: trusty
env:
  global:
    - REDIS_URL=redis://127.0.0.1
language: rust
cache: cargo

addons:
  apt:
    packages:
      - redis-server
  homebrew:
    packages:
      - redis
    update: true

jobs:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      os: linux
    - env: TARGET=x86_64-apple-darwin
      os: osx
    - env: TARGET=x86_64-unknown-linux-gnu
      os: linux
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly
  allow_failures:
    - rust: nightly
  fast_finish: true

notifications:
  email:
    on_success: never

branches:
  only:
    - master

git:
  depth: 3
  quiet: true

before_script:
  - cargo build --target $TARGET
  - bash .travis/load_redis_module.sh
script:
  - cargo test
